#!/bin/bash
# git-commit-msg-linter@5.0.4 2023/8/21 11:23:03
# id=commit-msg-linter - THE id COMMENT SHOULD NOT BE DELETED OR MODIFIED!
# It's used to check whether this commit-msg hook file is created by us,
# if it is then we can remove it confidently on uninstallation.

cat D:/Megvii/npm_git/git-commit-lint/node_modules/commit-msg-linter/commit-msg-linter.js | node --input-type=commonjs
